'use client';

import { LegalPage } from '@/components/landing/legal-page';
import { Navbar } from '@/components/landing/navbar';
import { Footer } from '@/components/landing/footer';

export default function PrivacyPage() {
    return (
        <div className="min-h-screen selection:bg-indigo-100 selection:text-indigo-900 scroll-smooth">
            <Navbar />
            <LegalPage title="Privacy Policy" content={`Privacy Policy
Affvance is a service operated by Meeting Me ("we," "us," or "our"). We respect your privacy and are committed to protecting your personal data.
This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit www.affvance.com or use our AI-powered content generation platform and related services (the "Services").
By accessing or using our Services, you acknowledge that you have read and understood this Privacy Policy and agree to the collection and use of information as described below.

1. Information We Collect
a. Personal Data You Provide
We collect personal data that you voluntarily provide when you:
• Create an account
• Subscribe to our Services
• Contact our support team
• Communicate with us regarding your account
This information may include:
• Full name
• Email address
• Account login credentials
• Billing country
• Communication preferences
We only collect personal data necessary to operate and provide our Services.

b. Payment Information
Payments for subscriptions and purchases on Affvance are processed by Paddle, who acts as the Merchant of Record for all transactions.
When you make a purchase, Paddle may collect and process payment-related information including:
• Billing name and email address
• Payment method details (such as card or payment provider information)
• IP address and device data for fraud prevention
• Transaction details and subscription information
• Tax-related information required for VAT, GST, or similar obligations
Payment card details are processed directly by Paddle and are not stored on Affvance servers.
Paddle processes this information in accordance with its own privacy policies and financial compliance requirements.
We receive limited information from Paddle necessary to:
• Manage subscriptions
• Provide invoices and billing support
• Handle refund or payment inquiries

c. Usage and Technical Data
When you access our website or Services, we may automatically collect certain technical information such as:
• IP address
• Browser type and version
• Device and operating system
• Pages visited and interactions
• Referral URLs
• Date and time of access
This information helps us monitor service performance, improve the user experience, and detect security risks.

d. AI-Generated Content
When you use our AI content generation features, we process:
• Text prompts submitted by you
• Content generated by the platform
This content is stored within your account so that you can access and manage your generated outputs.
Your content:
• Remains private to your account
• Is not publicly shared or sold
• Is used solely for providing and improving the Services
We do not use your private content to train public AI models without your permission.

2. Legal Basis for Processing (GDPR)
If you are located in the European Economic Area (EEA) or the United Kingdom, we process personal data under one or more of the following legal bases:
• Contractual necessity – to provide the Services you request
• Consent – for optional marketing communications or cookies
• Legitimate interests – platform security, analytics, and service improvements
• Legal obligations – compliance with tax, financial, and regulatory requirements

3. How We Use Your Information
We use collected information to:
• Provide and operate the Services
• Generate AI content based on user requests
• Manage user accounts and subscriptions
• Process billing and invoices through Paddle
• Communicate important service updates
• Respond to support requests
• Improve product functionality and performance
• Detect fraud, abuse, or unauthorized activity
• Comply with legal obligations

4. Data Sharing with Third Parties
We share data only when necessary to operate the Services.
Payment Processing
Payments are handled by Paddle, which processes billing, taxes, subscriptions, refunds, and financial compliance.
Infrastructure and Service Providers
We may work with trusted third-party service providers for:
• Cloud hosting infrastructure
• Security monitoring
• Analytics and performance monitoring
• Customer support tools
These providers process personal data only under contractual agreements requiring them to protect user information and use it solely for service delivery.

5. Cookies and Tracking Technologies
We use cookies and similar technologies to:
• Enable core site functionality
• Maintain user sessions
• Remember preferences
• Analyze service performance and usage
Where required by law, cookies used for analytics or marketing are deployed only after obtaining user consent.
You may control cookie settings through your browser configuration.

6. Data Retention
We retain personal data only for as long as necessary to:
• Maintain your account and provide Services
• Comply with legal and regulatory obligations
• Resolve disputes or enforce agreements
If you delete your account:
• Your personal account data and generated content will be removed
• Certain financial transaction records may be retained where required for accounting or legal compliance.

7. Your Privacy Rights
Depending on your location, you may have the right to:
• Access personal data we hold about you
• Request correction of inaccurate information
• Request deletion of your personal data
• Restrict or object to certain data processing
• Withdraw previously given consent
• Request a copy of your data in a portable format
To exercise these rights, contact us using the details provided below.

8. International Data Transfers
Affvance operates globally and may process data in multiple jurisdictions.
Personal data may be transferred outside your country of residence to secure cloud infrastructure and service providers.
When transferring personal data internationally, we implement appropriate safeguards including:
• Standard contractual clauses
• Secure infrastructure and encryption
• Data processing agreements with service providers

9. Children's Privacy
Our Services are not intended for individuals under the age of 13 (or higher age thresholds required by local laws).
We do not knowingly collect personal data from children. If such information is identified, it will be deleted promptly.

10. Security Measures
We implement appropriate technical and organizational safeguards to protect personal data, including:
• HTTPS encryption
• Secure authentication systems
• Access control policies
• Monitoring and security reviews
While we take reasonable measures to protect your information, no online system can guarantee absolute security.

11. Changes to This Privacy Policy
We may update this Privacy Policy from time to time.
Updates will be posted on this page along with a revised Last Updated date.
Continued use of the Services after changes indicates acceptance of the updated policy.

12. Contact Information
If you have questions about this Privacy Policy or wish to exercise your privacy rights, please contact us:
Email: assist@affvance.com

[ Last Updated: March 6, 2026 ]`} />
            <Footer />
        </div>
    );
}
